---
sudo: false

dist: xenial

language: ruby

cache: bundler

rvm:
  - ruby-2.6.0
  - ruby-2.6.1
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

before_install:
  - gem update --system
  - gem --version
  - gem install bundler
  - bundle -v
